#!/usr/bin/env Rscript

# Load necessary packages
library(ggplot2)
library(reshape2)
library(rstatix)
library(ggpubr)
library(optparse)

# Set up command-line options
option_list <- list(
  make_option(c("--input"), type="character", default=NULL, 
              help="Path to the input CSV file", metavar="character")
)

# Parse the command-line arguments
opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)

# Check if input file is provided
if (is.null(opt$input)) {
  print_help(opt_parser)
  stop("The input is the output generated by running 50_TFtarget_correlation.py", call.=FALSE)
}

# Set default output folder
output_dir <- "Visualization"

# Ensure the output directory exists
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# Read input data
cor_expression <- read.csv(opt$input)

# Reshape data for line plot
data_long <- reshape2::melt(cor_expression[,1:3], id.vars = "TF", variable.name = "Data_type", value.name = "Value")

# Generate line plot
lineplot <- ggplot(data_long, aes(x = TF, y = Value, group = Data_type, color = Data_type)) +
  geom_line(size = 1) +       
  geom_point(size = 2) +      
  labs(x = "TF-target genes", y = "Average correlation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = c(0.12, 0.87),
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.y = element_text(size = 12)) +
  scale_color_manual(values = c("TF_ori_cor" = "purple3", "TF_imputed_cor" = "orange"))

pdf(file.path(output_dir, "lineplot.pdf"), width = 12, height = 4)
print(lineplot)
dev.off()

# Prepare data for correlation analysis
df_long <- data.frame(
  TF = rep(cor_expression$TF, 2),
  Express = c(cor_expression$TF_ori_express, cor_expression$TF_imputed_express),
  Correlation = c(cor_expression$TF_ori_cor, cor_expression$TF_imputed_cor),
  Type = rep(c("Original", "Imputed"), each = nrow(cor_expression))
)

# Linear models
lm_original <- lm(Correlation ~ Express, data = subset(df_long, Type == "Original"))
lm_imputed <- lm(Correlation ~ Express, data = subset(df_long, Type == "Imputed"))

# Coefficients
coef_original <- coef(lm_original)
coef_imputed <- coef(lm_imputed)

# Correlation and p-value
r_original <- round(cor(subset(df_long, Type == "Original")$Express, 
                        subset(df_long, Type == "Original")$Correlation), 2)
p_value_original <- signif(summary(lm_original)$coefficients[2, 4], 3)
eq_original <- paste0("y = ", round(coef_original[2], 2), "x + ", round(coef_original[1], 2))

r_imputed <- round(cor(subset(df_long, Type == "Imputed")$Express, 
                       subset(df_long, Type == "Imputed")$Correlation), 2)
p_value_imputed <- signif(summary(lm_imputed)$coefficients[2, 4], 3)
eq_imputed <- paste0("y = ", round(coef_imputed[2], 2), "x + ", round(coef_imputed[1], 2))

# Generate expression correlation plot
Expression_correlation <- ggplot(df_long, aes(x = Express, y = Correlation, color = Type)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Expression", y = "Correlation") +
  theme_minimal() +
  scale_color_manual(values = c("Original" = "purple3", "Imputed" = "orange")) +
  annotate("text", x = Inf, y = Inf, label = paste0("Original: r = ", r_original, ", p = ", p_value_original, ", ", eq_original),
           color = "purple3", hjust = 1, vjust = 2.5, size = 5) +
  annotate("text", x = Inf, y = Inf, label = paste0("Imputed: r = ", r_imputed, ", p = ", p_value_imputed, ", ", eq_imputed), 
           color = "orange", hjust = 1, vjust = 1, size = 5) +
  theme(legend.position = c(0.8, 0.2),
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12))

pdf(file.path(output_dir, "Expression_correlation.pdf"), width = 6, height = 4)
print(Expression_correlation)
dev.off()

# Box plot for expression
df_long_expression <- data.frame(
  TF = rep(cor_expression$TF, 2),
  Expression = c(cor_expression$TF_ori_express, cor_expression$TF_imputed_express),
  Type = rep(c("Original", "Imputed"), each = nrow(cor_expression))
)

expression_Ori_VS_Imputed <- ggplot(df_long_expression, aes(x = Type, y = Expression, fill = Type)) +
  geom_boxplot() +
  labs(x = "Data type", y = "Average TF-target gene expression") +
  theme_minimal() +
  scale_fill_manual(values = c("Original" = "purple3", "Imputed" = "orange")) +
  theme(legend.position = c(0.9, 0.7),
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12))

pdf(file.path(output_dir, "Boxplot_expression_Ori_VS_Imputed.pdf"), width = 6, height = 4)
print(expression_Ori_VS_Imputed)
dev.off()

# Box plot for correlation
df_long_correlation <- data.frame(
  TF = rep(cor_expression$TF, 2),
  Correlation = c(cor_expression$TF_ori_cor, cor_expression$TF_imputed_cor),
  Type = rep(c("Original", "Imputed"), each = nrow(cor_expression))
)

correlation_Ori_VS_Imputed <- ggplot(df_long_correlation, aes(x = Type, y = Correlation, fill = Type)) +
  geom_boxplot() +
  labs(x = "Data type", y = "Average TF-target gene correlation") +
  theme_minimal() +
  scale_fill_manual(values = c("Original" = "purple3", "Imputed" = "orange")) +
  theme(legend.position = c(0.9, 0.7),
        axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12))

pdf(file.path(output_dir, "Boxplot_correlation_Ori_VS_Imputed.pdf"), width = 6, height = 4)
print(correlation_Ori_VS_Imputed)
dev.off()
